// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameProtocol.proto

package com.unsafe.gameserver.protocol;

public final class GameProto {
  private GameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MyEnumTestMessage}
   */
  public enum MyEnumTestMessage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ENUM_A = 0;</code>
     */
    ENUM_A(0),
    /**
     * <code>ENUM_B = 1;</code>
     */
    ENUM_B(1),
    /**
     * <code>ENUM_C = 2;</code>
     */
    ENUM_C(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ENUM_A = 0;</code>
     */
    public static final int ENUM_A_VALUE = 0;
    /**
     * <code>ENUM_B = 1;</code>
     */
    public static final int ENUM_B_VALUE = 1;
    /**
     * <code>ENUM_C = 2;</code>
     */
    public static final int ENUM_C_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MyEnumTestMessage valueOf(int value) {
      return forNumber(value);
    }

    public static MyEnumTestMessage forNumber(int value) {
      switch (value) {
        case 0: return ENUM_A;
        case 1: return ENUM_B;
        case 2: return ENUM_C;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MyEnumTestMessage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MyEnumTestMessage> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MyEnumTestMessage>() {
            public MyEnumTestMessage findValueByNumber(int number) {
              return MyEnumTestMessage.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.unsafe.gameserver.protocol.GameProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MyEnumTestMessage[] VALUES = values();

    public static MyEnumTestMessage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MyEnumTestMessage(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MyEnumTestMessage)
  }

  public interface TestMessageChildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMessageChild)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool checked = 3;</code>
     */
    boolean getChecked();
  }
  /**
   * Protobuf type {@code TestMessageChild}
   */
  public  static final class TestMessageChild extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMessageChild)
      TestMessageChildOrBuilder {
    // Use TestMessageChild.newBuilder() to construct.
    private TestMessageChild(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestMessageChild() {
      code_ = 0;
      name_ = "";
      checked_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestMessageChild(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              checked_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessageChild_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessageChild_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unsafe.gameserver.protocol.GameProto.TestMessageChild.class, com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKED_FIELD_NUMBER = 3;
    private boolean checked_;
    /**
     * <code>bool checked = 3;</code>
     */
    public boolean getChecked() {
      return checked_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (checked_ != false) {
        output.writeBool(3, checked_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (checked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, checked_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unsafe.gameserver.protocol.GameProto.TestMessageChild)) {
        return super.equals(obj);
      }
      com.unsafe.gameserver.protocol.GameProto.TestMessageChild other = (com.unsafe.gameserver.protocol.GameProto.TestMessageChild) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getName()
          .equals(other.getName());
      result = result && (getChecked()
          == other.getChecked());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CHECKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChecked());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unsafe.gameserver.protocol.GameProto.TestMessageChild prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestMessageChild}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMessageChild)
        com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessageChild_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessageChild_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unsafe.gameserver.protocol.GameProto.TestMessageChild.class, com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder.class);
      }

      // Construct using com.unsafe.gameserver.protocol.GameProto.TestMessageChild.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        name_ = "";

        checked_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessageChild_descriptor;
      }

      public com.unsafe.gameserver.protocol.GameProto.TestMessageChild getDefaultInstanceForType() {
        return com.unsafe.gameserver.protocol.GameProto.TestMessageChild.getDefaultInstance();
      }

      public com.unsafe.gameserver.protocol.GameProto.TestMessageChild build() {
        com.unsafe.gameserver.protocol.GameProto.TestMessageChild result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unsafe.gameserver.protocol.GameProto.TestMessageChild buildPartial() {
        com.unsafe.gameserver.protocol.GameProto.TestMessageChild result = new com.unsafe.gameserver.protocol.GameProto.TestMessageChild(this);
        result.code_ = code_;
        result.name_ = name_;
        result.checked_ = checked_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unsafe.gameserver.protocol.GameProto.TestMessageChild) {
          return mergeFrom((com.unsafe.gameserver.protocol.GameProto.TestMessageChild)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unsafe.gameserver.protocol.GameProto.TestMessageChild other) {
        if (other == com.unsafe.gameserver.protocol.GameProto.TestMessageChild.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getChecked() != false) {
          setChecked(other.getChecked());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unsafe.gameserver.protocol.GameProto.TestMessageChild parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unsafe.gameserver.protocol.GameProto.TestMessageChild) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private boolean checked_ ;
      /**
       * <code>bool checked = 3;</code>
       */
      public boolean getChecked() {
        return checked_;
      }
      /**
       * <code>bool checked = 3;</code>
       */
      public Builder setChecked(boolean value) {
        
        checked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool checked = 3;</code>
       */
      public Builder clearChecked() {
        
        checked_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestMessageChild)
    }

    // @@protoc_insertion_point(class_scope:TestMessageChild)
    private static final com.unsafe.gameserver.protocol.GameProto.TestMessageChild DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unsafe.gameserver.protocol.GameProto.TestMessageChild();
    }

    public static com.unsafe.gameserver.protocol.GameProto.TestMessageChild getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestMessageChild>
        PARSER = new com.google.protobuf.AbstractParser<TestMessageChild>() {
      public TestMessageChild parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestMessageChild(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMessageChild> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessageChild> getParserForType() {
      return PARSER;
    }

    public com.unsafe.gameserver.protocol.GameProto.TestMessageChild getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *double
     * </pre>
     *
     * <code>double var1 = 1;</code>
     */
    double getVar1();

    /**
     * <pre>
     *float
     * </pre>
     *
     * <code>float var2 = 2;</code>
     */
    float getVar2();

    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>int32 var3 = 3;</code>
     */
    int getVar3();

    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>uint32 var4 = 4;</code>
     */
    int getVar4();

    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>uint64 var5 = 5;</code>
     */
    long getVar5();

    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>sint32 var6 = 6;</code>
     */
    int getVar6();

    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>sint64 var7 = 7;</code>
     */
    long getVar7();

    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>fixed32 var8 = 8;</code>
     */
    int getVar8();

    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>fixed64 var9 = 9;</code>
     */
    long getVar9();

    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>sfixed32 var10 = 10;</code>
     */
    int getVar10();

    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>sfixed64 var11 = 11;</code>
     */
    long getVar11();

    /**
     * <pre>
     *boolean
     * </pre>
     *
     * <code>bool var12 = 12;</code>
     */
    boolean getVar12();

    /**
     * <pre>
     *string
     * </pre>
     *
     * <code>string var13 = 13;</code>
     */
    java.lang.String getVar13();
    /**
     * <pre>
     *string
     * </pre>
     *
     * <code>string var13 = 13;</code>
     */
    com.google.protobuf.ByteString
        getVar13Bytes();

    /**
     * <pre>
     *bytestring
     * </pre>
     *
     * <code>bytes var14 = 14;</code>
     */
    com.google.protobuf.ByteString getVar14();

    /**
     * <code>.TestMessageChild var15 = 15;</code>
     */
    boolean hasVar15();
    /**
     * <code>.TestMessageChild var15 = 15;</code>
     */
    com.unsafe.gameserver.protocol.GameProto.TestMessageChild getVar15();
    /**
     * <code>.TestMessageChild var15 = 15;</code>
     */
    com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder getVar15OrBuilder();

    /**
     * <code>.MyEnumTestMessage var16 = 16;</code>
     */
    int getVar16Value();
    /**
     * <code>.MyEnumTestMessage var16 = 16;</code>
     */
    com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage getVar16();
  }
  /**
   * Protobuf type {@code TestMessage}
   */
  public  static final class TestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMessage)
      TestMessageOrBuilder {
    // Use TestMessage.newBuilder() to construct.
    private TestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestMessage() {
      var1_ = 0D;
      var2_ = 0F;
      var3_ = 0;
      var4_ = 0;
      var5_ = 0L;
      var6_ = 0;
      var7_ = 0L;
      var8_ = 0;
      var9_ = 0L;
      var10_ = 0;
      var11_ = 0L;
      var12_ = false;
      var13_ = "";
      var14_ = com.google.protobuf.ByteString.EMPTY;
      var16_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              var1_ = input.readDouble();
              break;
            }
            case 21: {

              var2_ = input.readFloat();
              break;
            }
            case 24: {

              var3_ = input.readInt32();
              break;
            }
            case 32: {

              var4_ = input.readUInt32();
              break;
            }
            case 40: {

              var5_ = input.readUInt64();
              break;
            }
            case 48: {

              var6_ = input.readSInt32();
              break;
            }
            case 56: {

              var7_ = input.readSInt64();
              break;
            }
            case 69: {

              var8_ = input.readFixed32();
              break;
            }
            case 73: {

              var9_ = input.readFixed64();
              break;
            }
            case 85: {

              var10_ = input.readSFixed32();
              break;
            }
            case 89: {

              var11_ = input.readSFixed64();
              break;
            }
            case 96: {

              var12_ = input.readBool();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              var13_ = s;
              break;
            }
            case 114: {

              var14_ = input.readBytes();
              break;
            }
            case 122: {
              com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder subBuilder = null;
              if (var15_ != null) {
                subBuilder = var15_.toBuilder();
              }
              var15_ = input.readMessage(com.unsafe.gameserver.protocol.GameProto.TestMessageChild.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(var15_);
                var15_ = subBuilder.buildPartial();
              }

              break;
            }
            case 128: {
              int rawValue = input.readEnum();

              var16_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unsafe.gameserver.protocol.GameProto.TestMessage.class, com.unsafe.gameserver.protocol.GameProto.TestMessage.Builder.class);
    }

    public static final int VAR1_FIELD_NUMBER = 1;
    private double var1_;
    /**
     * <pre>
     *double
     * </pre>
     *
     * <code>double var1 = 1;</code>
     */
    public double getVar1() {
      return var1_;
    }

    public static final int VAR2_FIELD_NUMBER = 2;
    private float var2_;
    /**
     * <pre>
     *float
     * </pre>
     *
     * <code>float var2 = 2;</code>
     */
    public float getVar2() {
      return var2_;
    }

    public static final int VAR3_FIELD_NUMBER = 3;
    private int var3_;
    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>int32 var3 = 3;</code>
     */
    public int getVar3() {
      return var3_;
    }

    public static final int VAR4_FIELD_NUMBER = 4;
    private int var4_;
    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>uint32 var4 = 4;</code>
     */
    public int getVar4() {
      return var4_;
    }

    public static final int VAR5_FIELD_NUMBER = 5;
    private long var5_;
    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>uint64 var5 = 5;</code>
     */
    public long getVar5() {
      return var5_;
    }

    public static final int VAR6_FIELD_NUMBER = 6;
    private int var6_;
    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>sint32 var6 = 6;</code>
     */
    public int getVar6() {
      return var6_;
    }

    public static final int VAR7_FIELD_NUMBER = 7;
    private long var7_;
    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>sint64 var7 = 7;</code>
     */
    public long getVar7() {
      return var7_;
    }

    public static final int VAR8_FIELD_NUMBER = 8;
    private int var8_;
    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>fixed32 var8 = 8;</code>
     */
    public int getVar8() {
      return var8_;
    }

    public static final int VAR9_FIELD_NUMBER = 9;
    private long var9_;
    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>fixed64 var9 = 9;</code>
     */
    public long getVar9() {
      return var9_;
    }

    public static final int VAR10_FIELD_NUMBER = 10;
    private int var10_;
    /**
     * <pre>
     *int
     * </pre>
     *
     * <code>sfixed32 var10 = 10;</code>
     */
    public int getVar10() {
      return var10_;
    }

    public static final int VAR11_FIELD_NUMBER = 11;
    private long var11_;
    /**
     * <pre>
     *long
     * </pre>
     *
     * <code>sfixed64 var11 = 11;</code>
     */
    public long getVar11() {
      return var11_;
    }

    public static final int VAR12_FIELD_NUMBER = 12;
    private boolean var12_;
    /**
     * <pre>
     *boolean
     * </pre>
     *
     * <code>bool var12 = 12;</code>
     */
    public boolean getVar12() {
      return var12_;
    }

    public static final int VAR13_FIELD_NUMBER = 13;
    private volatile java.lang.Object var13_;
    /**
     * <pre>
     *string
     * </pre>
     *
     * <code>string var13 = 13;</code>
     */
    public java.lang.String getVar13() {
      java.lang.Object ref = var13_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        var13_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *string
     * </pre>
     *
     * <code>string var13 = 13;</code>
     */
    public com.google.protobuf.ByteString
        getVar13Bytes() {
      java.lang.Object ref = var13_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        var13_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VAR14_FIELD_NUMBER = 14;
    private com.google.protobuf.ByteString var14_;
    /**
     * <pre>
     *bytestring
     * </pre>
     *
     * <code>bytes var14 = 14;</code>
     */
    public com.google.protobuf.ByteString getVar14() {
      return var14_;
    }

    public static final int VAR15_FIELD_NUMBER = 15;
    private com.unsafe.gameserver.protocol.GameProto.TestMessageChild var15_;
    /**
     * <code>.TestMessageChild var15 = 15;</code>
     */
    public boolean hasVar15() {
      return var15_ != null;
    }
    /**
     * <code>.TestMessageChild var15 = 15;</code>
     */
    public com.unsafe.gameserver.protocol.GameProto.TestMessageChild getVar15() {
      return var15_ == null ? com.unsafe.gameserver.protocol.GameProto.TestMessageChild.getDefaultInstance() : var15_;
    }
    /**
     * <code>.TestMessageChild var15 = 15;</code>
     */
    public com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder getVar15OrBuilder() {
      return getVar15();
    }

    public static final int VAR16_FIELD_NUMBER = 16;
    private int var16_;
    /**
     * <code>.MyEnumTestMessage var16 = 16;</code>
     */
    public int getVar16Value() {
      return var16_;
    }
    /**
     * <code>.MyEnumTestMessage var16 = 16;</code>
     */
    public com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage getVar16() {
      com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage result = com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage.valueOf(var16_);
      return result == null ? com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (var1_ != 0D) {
        output.writeDouble(1, var1_);
      }
      if (var2_ != 0F) {
        output.writeFloat(2, var2_);
      }
      if (var3_ != 0) {
        output.writeInt32(3, var3_);
      }
      if (var4_ != 0) {
        output.writeUInt32(4, var4_);
      }
      if (var5_ != 0L) {
        output.writeUInt64(5, var5_);
      }
      if (var6_ != 0) {
        output.writeSInt32(6, var6_);
      }
      if (var7_ != 0L) {
        output.writeSInt64(7, var7_);
      }
      if (var8_ != 0) {
        output.writeFixed32(8, var8_);
      }
      if (var9_ != 0L) {
        output.writeFixed64(9, var9_);
      }
      if (var10_ != 0) {
        output.writeSFixed32(10, var10_);
      }
      if (var11_ != 0L) {
        output.writeSFixed64(11, var11_);
      }
      if (var12_ != false) {
        output.writeBool(12, var12_);
      }
      if (!getVar13Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, var13_);
      }
      if (!var14_.isEmpty()) {
        output.writeBytes(14, var14_);
      }
      if (var15_ != null) {
        output.writeMessage(15, getVar15());
      }
      if (var16_ != com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage.ENUM_A.getNumber()) {
        output.writeEnum(16, var16_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (var1_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, var1_);
      }
      if (var2_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, var2_);
      }
      if (var3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, var3_);
      }
      if (var4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, var4_);
      }
      if (var5_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, var5_);
      }
      if (var6_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, var6_);
      }
      if (var7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, var7_);
      }
      if (var8_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(8, var8_);
      }
      if (var9_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(9, var9_);
      }
      if (var10_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(10, var10_);
      }
      if (var11_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(11, var11_);
      }
      if (var12_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, var12_);
      }
      if (!getVar13Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, var13_);
      }
      if (!var14_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, var14_);
      }
      if (var15_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getVar15());
      }
      if (var16_ != com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage.ENUM_A.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(16, var16_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unsafe.gameserver.protocol.GameProto.TestMessage)) {
        return super.equals(obj);
      }
      com.unsafe.gameserver.protocol.GameProto.TestMessage other = (com.unsafe.gameserver.protocol.GameProto.TestMessage) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getVar1())
          == java.lang.Double.doubleToLongBits(
              other.getVar1()));
      result = result && (
          java.lang.Float.floatToIntBits(getVar2())
          == java.lang.Float.floatToIntBits(
              other.getVar2()));
      result = result && (getVar3()
          == other.getVar3());
      result = result && (getVar4()
          == other.getVar4());
      result = result && (getVar5()
          == other.getVar5());
      result = result && (getVar6()
          == other.getVar6());
      result = result && (getVar7()
          == other.getVar7());
      result = result && (getVar8()
          == other.getVar8());
      result = result && (getVar9()
          == other.getVar9());
      result = result && (getVar10()
          == other.getVar10());
      result = result && (getVar11()
          == other.getVar11());
      result = result && (getVar12()
          == other.getVar12());
      result = result && getVar13()
          .equals(other.getVar13());
      result = result && getVar14()
          .equals(other.getVar14());
      result = result && (hasVar15() == other.hasVar15());
      if (hasVar15()) {
        result = result && getVar15()
            .equals(other.getVar15());
      }
      result = result && var16_ == other.var16_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAR1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVar1()));
      hash = (37 * hash) + VAR2_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVar2());
      hash = (37 * hash) + VAR3_FIELD_NUMBER;
      hash = (53 * hash) + getVar3();
      hash = (37 * hash) + VAR4_FIELD_NUMBER;
      hash = (53 * hash) + getVar4();
      hash = (37 * hash) + VAR5_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVar5());
      hash = (37 * hash) + VAR6_FIELD_NUMBER;
      hash = (53 * hash) + getVar6();
      hash = (37 * hash) + VAR7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVar7());
      hash = (37 * hash) + VAR8_FIELD_NUMBER;
      hash = (53 * hash) + getVar8();
      hash = (37 * hash) + VAR9_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVar9());
      hash = (37 * hash) + VAR10_FIELD_NUMBER;
      hash = (53 * hash) + getVar10();
      hash = (37 * hash) + VAR11_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVar11());
      hash = (37 * hash) + VAR12_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVar12());
      hash = (37 * hash) + VAR13_FIELD_NUMBER;
      hash = (53 * hash) + getVar13().hashCode();
      hash = (37 * hash) + VAR14_FIELD_NUMBER;
      hash = (53 * hash) + getVar14().hashCode();
      if (hasVar15()) {
        hash = (37 * hash) + VAR15_FIELD_NUMBER;
        hash = (53 * hash) + getVar15().hashCode();
      }
      hash = (37 * hash) + VAR16_FIELD_NUMBER;
      hash = (53 * hash) + var16_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unsafe.gameserver.protocol.GameProto.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unsafe.gameserver.protocol.GameProto.TestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMessage)
        com.unsafe.gameserver.protocol.GameProto.TestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unsafe.gameserver.protocol.GameProto.TestMessage.class, com.unsafe.gameserver.protocol.GameProto.TestMessage.Builder.class);
      }

      // Construct using com.unsafe.gameserver.protocol.GameProto.TestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        var1_ = 0D;

        var2_ = 0F;

        var3_ = 0;

        var4_ = 0;

        var5_ = 0L;

        var6_ = 0;

        var7_ = 0L;

        var8_ = 0;

        var9_ = 0L;

        var10_ = 0;

        var11_ = 0L;

        var12_ = false;

        var13_ = "";

        var14_ = com.google.protobuf.ByteString.EMPTY;

        if (var15Builder_ == null) {
          var15_ = null;
        } else {
          var15_ = null;
          var15Builder_ = null;
        }
        var16_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unsafe.gameserver.protocol.GameProto.internal_static_TestMessage_descriptor;
      }

      public com.unsafe.gameserver.protocol.GameProto.TestMessage getDefaultInstanceForType() {
        return com.unsafe.gameserver.protocol.GameProto.TestMessage.getDefaultInstance();
      }

      public com.unsafe.gameserver.protocol.GameProto.TestMessage build() {
        com.unsafe.gameserver.protocol.GameProto.TestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.unsafe.gameserver.protocol.GameProto.TestMessage buildPartial() {
        com.unsafe.gameserver.protocol.GameProto.TestMessage result = new com.unsafe.gameserver.protocol.GameProto.TestMessage(this);
        result.var1_ = var1_;
        result.var2_ = var2_;
        result.var3_ = var3_;
        result.var4_ = var4_;
        result.var5_ = var5_;
        result.var6_ = var6_;
        result.var7_ = var7_;
        result.var8_ = var8_;
        result.var9_ = var9_;
        result.var10_ = var10_;
        result.var11_ = var11_;
        result.var12_ = var12_;
        result.var13_ = var13_;
        result.var14_ = var14_;
        if (var15Builder_ == null) {
          result.var15_ = var15_;
        } else {
          result.var15_ = var15Builder_.build();
        }
        result.var16_ = var16_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unsafe.gameserver.protocol.GameProto.TestMessage) {
          return mergeFrom((com.unsafe.gameserver.protocol.GameProto.TestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unsafe.gameserver.protocol.GameProto.TestMessage other) {
        if (other == com.unsafe.gameserver.protocol.GameProto.TestMessage.getDefaultInstance()) return this;
        if (other.getVar1() != 0D) {
          setVar1(other.getVar1());
        }
        if (other.getVar2() != 0F) {
          setVar2(other.getVar2());
        }
        if (other.getVar3() != 0) {
          setVar3(other.getVar3());
        }
        if (other.getVar4() != 0) {
          setVar4(other.getVar4());
        }
        if (other.getVar5() != 0L) {
          setVar5(other.getVar5());
        }
        if (other.getVar6() != 0) {
          setVar6(other.getVar6());
        }
        if (other.getVar7() != 0L) {
          setVar7(other.getVar7());
        }
        if (other.getVar8() != 0) {
          setVar8(other.getVar8());
        }
        if (other.getVar9() != 0L) {
          setVar9(other.getVar9());
        }
        if (other.getVar10() != 0) {
          setVar10(other.getVar10());
        }
        if (other.getVar11() != 0L) {
          setVar11(other.getVar11());
        }
        if (other.getVar12() != false) {
          setVar12(other.getVar12());
        }
        if (!other.getVar13().isEmpty()) {
          var13_ = other.var13_;
          onChanged();
        }
        if (other.getVar14() != com.google.protobuf.ByteString.EMPTY) {
          setVar14(other.getVar14());
        }
        if (other.hasVar15()) {
          mergeVar15(other.getVar15());
        }
        if (other.var16_ != 0) {
          setVar16Value(other.getVar16Value());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unsafe.gameserver.protocol.GameProto.TestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unsafe.gameserver.protocol.GameProto.TestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double var1_ ;
      /**
       * <pre>
       *double
       * </pre>
       *
       * <code>double var1 = 1;</code>
       */
      public double getVar1() {
        return var1_;
      }
      /**
       * <pre>
       *double
       * </pre>
       *
       * <code>double var1 = 1;</code>
       */
      public Builder setVar1(double value) {
        
        var1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *double
       * </pre>
       *
       * <code>double var1 = 1;</code>
       */
      public Builder clearVar1() {
        
        var1_ = 0D;
        onChanged();
        return this;
      }

      private float var2_ ;
      /**
       * <pre>
       *float
       * </pre>
       *
       * <code>float var2 = 2;</code>
       */
      public float getVar2() {
        return var2_;
      }
      /**
       * <pre>
       *float
       * </pre>
       *
       * <code>float var2 = 2;</code>
       */
      public Builder setVar2(float value) {
        
        var2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *float
       * </pre>
       *
       * <code>float var2 = 2;</code>
       */
      public Builder clearVar2() {
        
        var2_ = 0F;
        onChanged();
        return this;
      }

      private int var3_ ;
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>int32 var3 = 3;</code>
       */
      public int getVar3() {
        return var3_;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>int32 var3 = 3;</code>
       */
      public Builder setVar3(int value) {
        
        var3_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>int32 var3 = 3;</code>
       */
      public Builder clearVar3() {
        
        var3_ = 0;
        onChanged();
        return this;
      }

      private int var4_ ;
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>uint32 var4 = 4;</code>
       */
      public int getVar4() {
        return var4_;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>uint32 var4 = 4;</code>
       */
      public Builder setVar4(int value) {
        
        var4_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>uint32 var4 = 4;</code>
       */
      public Builder clearVar4() {
        
        var4_ = 0;
        onChanged();
        return this;
      }

      private long var5_ ;
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>uint64 var5 = 5;</code>
       */
      public long getVar5() {
        return var5_;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>uint64 var5 = 5;</code>
       */
      public Builder setVar5(long value) {
        
        var5_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>uint64 var5 = 5;</code>
       */
      public Builder clearVar5() {
        
        var5_ = 0L;
        onChanged();
        return this;
      }

      private int var6_ ;
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>sint32 var6 = 6;</code>
       */
      public int getVar6() {
        return var6_;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>sint32 var6 = 6;</code>
       */
      public Builder setVar6(int value) {
        
        var6_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>sint32 var6 = 6;</code>
       */
      public Builder clearVar6() {
        
        var6_ = 0;
        onChanged();
        return this;
      }

      private long var7_ ;
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>sint64 var7 = 7;</code>
       */
      public long getVar7() {
        return var7_;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>sint64 var7 = 7;</code>
       */
      public Builder setVar7(long value) {
        
        var7_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>sint64 var7 = 7;</code>
       */
      public Builder clearVar7() {
        
        var7_ = 0L;
        onChanged();
        return this;
      }

      private int var8_ ;
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>fixed32 var8 = 8;</code>
       */
      public int getVar8() {
        return var8_;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>fixed32 var8 = 8;</code>
       */
      public Builder setVar8(int value) {
        
        var8_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>fixed32 var8 = 8;</code>
       */
      public Builder clearVar8() {
        
        var8_ = 0;
        onChanged();
        return this;
      }

      private long var9_ ;
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>fixed64 var9 = 9;</code>
       */
      public long getVar9() {
        return var9_;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>fixed64 var9 = 9;</code>
       */
      public Builder setVar9(long value) {
        
        var9_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>fixed64 var9 = 9;</code>
       */
      public Builder clearVar9() {
        
        var9_ = 0L;
        onChanged();
        return this;
      }

      private int var10_ ;
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>sfixed32 var10 = 10;</code>
       */
      public int getVar10() {
        return var10_;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>sfixed32 var10 = 10;</code>
       */
      public Builder setVar10(int value) {
        
        var10_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int
       * </pre>
       *
       * <code>sfixed32 var10 = 10;</code>
       */
      public Builder clearVar10() {
        
        var10_ = 0;
        onChanged();
        return this;
      }

      private long var11_ ;
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>sfixed64 var11 = 11;</code>
       */
      public long getVar11() {
        return var11_;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>sfixed64 var11 = 11;</code>
       */
      public Builder setVar11(long value) {
        
        var11_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *long
       * </pre>
       *
       * <code>sfixed64 var11 = 11;</code>
       */
      public Builder clearVar11() {
        
        var11_ = 0L;
        onChanged();
        return this;
      }

      private boolean var12_ ;
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>bool var12 = 12;</code>
       */
      public boolean getVar12() {
        return var12_;
      }
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>bool var12 = 12;</code>
       */
      public Builder setVar12(boolean value) {
        
        var12_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>bool var12 = 12;</code>
       */
      public Builder clearVar12() {
        
        var12_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object var13_ = "";
      /**
       * <pre>
       *string
       * </pre>
       *
       * <code>string var13 = 13;</code>
       */
      public java.lang.String getVar13() {
        java.lang.Object ref = var13_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          var13_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *string
       * </pre>
       *
       * <code>string var13 = 13;</code>
       */
      public com.google.protobuf.ByteString
          getVar13Bytes() {
        java.lang.Object ref = var13_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          var13_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *string
       * </pre>
       *
       * <code>string var13 = 13;</code>
       */
      public Builder setVar13(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        var13_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *string
       * </pre>
       *
       * <code>string var13 = 13;</code>
       */
      public Builder clearVar13() {
        
        var13_ = getDefaultInstance().getVar13();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *string
       * </pre>
       *
       * <code>string var13 = 13;</code>
       */
      public Builder setVar13Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        var13_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString var14_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *bytestring
       * </pre>
       *
       * <code>bytes var14 = 14;</code>
       */
      public com.google.protobuf.ByteString getVar14() {
        return var14_;
      }
      /**
       * <pre>
       *bytestring
       * </pre>
       *
       * <code>bytes var14 = 14;</code>
       */
      public Builder setVar14(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        var14_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bytestring
       * </pre>
       *
       * <code>bytes var14 = 14;</code>
       */
      public Builder clearVar14() {
        
        var14_ = getDefaultInstance().getVar14();
        onChanged();
        return this;
      }

      private com.unsafe.gameserver.protocol.GameProto.TestMessageChild var15_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.unsafe.gameserver.protocol.GameProto.TestMessageChild, com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder, com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder> var15Builder_;
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public boolean hasVar15() {
        return var15Builder_ != null || var15_ != null;
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public com.unsafe.gameserver.protocol.GameProto.TestMessageChild getVar15() {
        if (var15Builder_ == null) {
          return var15_ == null ? com.unsafe.gameserver.protocol.GameProto.TestMessageChild.getDefaultInstance() : var15_;
        } else {
          return var15Builder_.getMessage();
        }
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public Builder setVar15(com.unsafe.gameserver.protocol.GameProto.TestMessageChild value) {
        if (var15Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          var15_ = value;
          onChanged();
        } else {
          var15Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public Builder setVar15(
          com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder builderForValue) {
        if (var15Builder_ == null) {
          var15_ = builderForValue.build();
          onChanged();
        } else {
          var15Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public Builder mergeVar15(com.unsafe.gameserver.protocol.GameProto.TestMessageChild value) {
        if (var15Builder_ == null) {
          if (var15_ != null) {
            var15_ =
              com.unsafe.gameserver.protocol.GameProto.TestMessageChild.newBuilder(var15_).mergeFrom(value).buildPartial();
          } else {
            var15_ = value;
          }
          onChanged();
        } else {
          var15Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public Builder clearVar15() {
        if (var15Builder_ == null) {
          var15_ = null;
          onChanged();
        } else {
          var15_ = null;
          var15Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder getVar15Builder() {
        
        onChanged();
        return getVar15FieldBuilder().getBuilder();
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      public com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder getVar15OrBuilder() {
        if (var15Builder_ != null) {
          return var15Builder_.getMessageOrBuilder();
        } else {
          return var15_ == null ?
              com.unsafe.gameserver.protocol.GameProto.TestMessageChild.getDefaultInstance() : var15_;
        }
      }
      /**
       * <code>.TestMessageChild var15 = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.unsafe.gameserver.protocol.GameProto.TestMessageChild, com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder, com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder> 
          getVar15FieldBuilder() {
        if (var15Builder_ == null) {
          var15Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.unsafe.gameserver.protocol.GameProto.TestMessageChild, com.unsafe.gameserver.protocol.GameProto.TestMessageChild.Builder, com.unsafe.gameserver.protocol.GameProto.TestMessageChildOrBuilder>(
                  getVar15(),
                  getParentForChildren(),
                  isClean());
          var15_ = null;
        }
        return var15Builder_;
      }

      private int var16_ = 0;
      /**
       * <code>.MyEnumTestMessage var16 = 16;</code>
       */
      public int getVar16Value() {
        return var16_;
      }
      /**
       * <code>.MyEnumTestMessage var16 = 16;</code>
       */
      public Builder setVar16Value(int value) {
        var16_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MyEnumTestMessage var16 = 16;</code>
       */
      public com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage getVar16() {
        com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage result = com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage.valueOf(var16_);
        return result == null ? com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage.UNRECOGNIZED : result;
      }
      /**
       * <code>.MyEnumTestMessage var16 = 16;</code>
       */
      public Builder setVar16(com.unsafe.gameserver.protocol.GameProto.MyEnumTestMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        var16_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MyEnumTestMessage var16 = 16;</code>
       */
      public Builder clearVar16() {
        
        var16_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestMessage)
    }

    // @@protoc_insertion_point(class_scope:TestMessage)
    private static final com.unsafe.gameserver.protocol.GameProto.TestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unsafe.gameserver.protocol.GameProto.TestMessage();
    }

    public static com.unsafe.gameserver.protocol.GameProto.TestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestMessage>
        PARSER = new com.google.protobuf.AbstractParser<TestMessage>() {
      public TestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage> getParserForType() {
      return PARSER;
    }

    public com.unsafe.gameserver.protocol.GameProto.TestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMessageChild_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMessageChild_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022GameProtocol.proto\"?\n\020TestMessageChild" +
      "\022\014\n\004code\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017\n\007checked\030" +
      "\003 \001(\010\"\233\002\n\013TestMessage\022\014\n\004var1\030\001 \001(\001\022\014\n\004v" +
      "ar2\030\002 \001(\002\022\014\n\004var3\030\003 \001(\005\022\014\n\004var4\030\004 \001(\r\022\014\n" +
      "\004var5\030\005 \001(\004\022\014\n\004var6\030\006 \001(\021\022\014\n\004var7\030\007 \001(\022\022" +
      "\014\n\004var8\030\010 \001(\007\022\014\n\004var9\030\t \001(\006\022\r\n\005var10\030\n \001" +
      "(\017\022\r\n\005var11\030\013 \001(\020\022\r\n\005var12\030\014 \001(\010\022\r\n\005var1" +
      "3\030\r \001(\t\022\r\n\005var14\030\016 \001(\014\022 \n\005var15\030\017 \001(\0132\021." +
      "TestMessageChild\022!\n\005var16\030\020 \001(\0162\022.MyEnum" +
      "TestMessage*7\n\021MyEnumTestMessage\022\n\n\006ENUM",
      "_A\020\000\022\n\n\006ENUM_B\020\001\022\n\n\006ENUM_C\020\002B-\n\036com.unsa" +
      "fe.gameserver.protocolB\tGameProtoH\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestMessageChild_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestMessageChild_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMessageChild_descriptor,
        new java.lang.String[] { "Code", "Name", "Checked", });
    internal_static_TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMessage_descriptor,
        new java.lang.String[] { "Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
